[build]
  command = "npm run build"
  publish = "frontend/out"
  functions = "frontend/netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 