[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"
  functions = "frontend/netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "1"
  NODE_VERSION = "18"

# Ignore certain paths for secrets scanning
[secrets]
SECRETS_SCAN_OMIT_PATHS = [
  ".next/**/*",
  "out/**/*",
  ".netlify/**/*"
]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable" 